/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dsn.layer2_constants.h"

namespace dsn {

const dsn.layer2Constants g_dsn.layer2_constants;

dsn.layer2Constants::dsn.layer2Constants() {
}

} // namespace

