/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dsn.layer2_CONSTANTS_H
#define dsn.layer2_CONSTANTS_H

#include "dsn.layer2_types.h"

namespace dsn {

class dsn.layer2Constants {
 public:
  dsn.layer2Constants();

};

extern const dsn.layer2Constants g_dsn.layer2_constants;

} // namespace

#endif
