/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dsn_CONSTANTS_H
#define dsn_CONSTANTS_H

#include "dsn_types.h"

namespace dsn {

class dsnConstants {
 public:
  dsnConstants();

};

extern const dsnConstants g_dsn_constants;

} // namespace

#endif
